"""Add company_flags

Revision ID: a5e57be01428
Revises: 488fcb5ed3ff
Create Date: 2026-07-31 13:57:40.646164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5e57be01428'
down_revision: Union[str, Sequence[str], None] = '488fcb5ed3ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('flag_type', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_flags_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_flags_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_flags_id'))
        batch_op.drop_index(batch_op.f('ix_company_flags_domain'))

    op.drop_table('company_flags')
    # ### end Alembic commands ###
