"""Initial commit

Revision ID: ac77ca18dbb3
Revises: 
Create Date: 2026-07-31 12:22:34.229917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac77ca18dbb3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fraud_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('velocity', sa.Integer(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('geo_distance', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('reasons_jsonb', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_events_id'), 'fraud_events', ['id'], unique=False)
    op.create_table('phishing_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_url', sa.String(), nullable=True),
    sa.Column('input_text', sa.String(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('reasons_jsonb', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phishing_events_id'), 'phishing_events', ['id'], unique=False)
    op.create_index(op.f('ix_phishing_events_input_url'), 'phishing_events', ['input_url'], unique=False)
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=False),
    sa.Column('input_jsonb', sa.TEXT(), nullable=False),
    sa.Column('score', sa.REAL(), nullable=False),
    sa.Column('tier', sa.TEXT(), nullable=False),
    sa.Column('reasons_jsonb', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_phishing_events_input_url'), table_name='phishing_events')
    op.drop_index(op.f('ix_phishing_events_id'), table_name='phishing_events')
    op.drop_table('phishing_events')
    op.drop_index(op.f('ix_fraud_events_id'), table_name='fraud_events')
    op.drop_table('fraud_events')
    # ### end Alembic commands ###
